name: Create ELN Map

on:
  push:
    tags:
      - "*"

jobs:
  create-map:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          check-latest: true
          cache: "pip"
          python-version: "3.13"
      - name: Install dependencies, get prerequisites and run script
        run: |
          pip    install --upgrade pip
          pip    install --no-warn-script-location .
          bash   download_prerequistes.sh
          python generate_map.py
          python generate_map.py germany
          python generate_map.py nogermany
      - name: Release Map
        uses: "softprops/action-gh-release@v2"
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            germany.svg
            restofeur.svg
            europe.svg
            map.html
